env:
  browser: true
  commonjs: true
  node: true
  es6: true
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
plugins:
  - react
  - jsx
  - async-await
rules:
  strict: error
